trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure DevOps K8s Terraform!
  displayName: 'Run a one-line script'

- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'azure_rsa'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)//terraform/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'backend-tf-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageaccountlana1'
    backendAzureRmContainerName: 'storageaccountcontainerlana1'
    backendAzureRmKey: 'k8s-dev.tfstate'
