trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure DevOps Kubernetes Terraform!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
   secureFile: 'azure_rsa_2'
- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/backend'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: '4bd7928d-756a-4396-8d8f-803e40dd52db'
    backendAzureRmSubscriptionId: 'd593673b-0e4f-4d3b-96da-f863d69d9470'
    backendAzureRmResourceGroupName: 'tf-backend-rg'
    backendAzureRmStorageAccountName: 'storageacclanarad'
    backendAzureRmContainerName: 'storageacclanaradcontainer'
    backendAzureRmKey: 'storage-dev.tfstate'

- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/backend'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath) -var tenant_id=$(tenant_id)'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: '4bd7928d-756a-4396-8d8f-803e40dd52db'
    backendAzureRmSubscriptionId: 'd593673b-0e4f-4d3b-96da-f863d69d9470'
    
- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath)'

