trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Azure DevOps Kubernetes Terraform!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
   secureFile: 'azure_rsa_2'

- task: TerraformCLI@2
  inputs:
    command: 'init'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/kubernetes'
    backendType: 'azurerm'
    backendServiceArm: 'azure-resource-manager-service-connection'
    backendAzureRmTenantId: '4bd7928d-756a-4396-8d8f-803e40dd52db'
    backendAzureRmSubscriptionId: '42f2fbbc-570c-4c13-a737-a75374bf8a3b'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'tf-backend-rg'
    backendAzureRmResourceGroupLocation: 'westeurope'
    backendAzureRmStorageAccountName: 'storageacclanarad'
    backendAzureRmContainerName: 'storageacclanaradcontainer'
    backendAzureRmKey: 'k8s-dev.tfstate'
    allowTelemetryCollection: true
    
- task: TerraformCLI@2
  inputs:
    command: 'apply'
    workingDirectory: '$(System.DefaultWorkingDirectory)/terraform/configuration/iaac/azure/kubernetes'
    commandOptions: '-var client_id=${client_id} -var client_secret=${client_secret} -var ssh_public_key(publickey.secureFilePath)'
    allowTelemetryCollection: true

